# Generated by Django 4.2.2 on 2023-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
