# Generated by Django 4.2.2 on 2023-06-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_description',
            field=models.CharField(default='', max_length=1200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description_one',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_two',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
