# Generated by Django 4.2.2 on 2023-06-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_post_main_description_alter_post_description_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('comment_vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], max_length=4)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
    ]
