# Generated by Django 4.2.2 on 2023-06-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_commentvote_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='post',
        ),
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.comment'),
            preserve_default=False,
        ),
    ]
