# Generated by Django 4.2.2 on 2023-06-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_commentvote_post_commentvote_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='PostVote',
        ),
    ]
