# Generated by Django 4.2.2 on 2023-06-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_post_button_one_label_post_button_two_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='button_one_label',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='button_two_label',
            field=models.CharField(max_length=25),
        ),
    ]
