# Generated by Django 4.2.2 on 2023-06-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_post_button_one_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postvote',
            old_name='option',
            new_name='vote_option',
        ),
    ]
