# Generated by Django 4.1.7 on 2023-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_rename_option_postvote_vote_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_one',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
