# Generated by Django 4.1.7 on 2023-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_post_description_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_one',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_two',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_description',
            field=models.CharField(max_length=1300),
        ),
    ]
