# Generated by Django 4.1.7 on 2023-06-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_post_description_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentvote',
            old_name='option',
            new_name='vote_option',
        ),
    ]
