#USER
MAX_USERNAME_LENGTH = 16
MAX_EMAIL_LENGTH = 60
MAX_PASSWORD_LENGTH = 24

#POST
MAX_MAIN_DESCRIPTION_LENTGH = 1200
MAX_DESCRIPTION_LENGTH = 500
MAX_TAGS_LENGTH = 120
MAX_STATUS_LENGTH = 6
MAX_TITLE_LENGTH = 50

#VOTE
MAX_OPTION_LENGTH = 1

#PASSWORD
MIN_PASSWORD_LENGTH = 8
MIN_UPPERCASE_CHARS = 1
MIN_SPECIAL_CHARS = 1

#GENERAL
MAX_SEARCH_SUGGESTIONS = 12
MAX_POST_PREVIEWS_PER_PAGE = 20
MAX_TAGS = 5
VALID_IMAGE_EXTENSIONS = ('.jpg', '.png', 'jpeg')
MAX_TAG_LENGTH = MAX_TAGS_LENGTH // MAX_TAGS
